config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  delete '/logout', to: "sessions#destroy", as: 'logout'

  post '/login', to: "sessions#create", as: "new_user_session"
  get '/login', to: "sessions#login", as: "login"

  delete "/user/:id", to: "users#destroy", as: "user_destroy"
  patch "/user/:id", to: "users#update"
  get "/user/:id/edit", to: "users#edit", as: "user_edit" 
  get "/user/:id", to: "users#show", as: "user"
  get '/users', to: "users#index"
  post '/users', to: "users#create"
  get '/signup', to: "users#new", as: "signup"

  delete "/article/:id", to: "articles#destroy", as: "article_destroy"
  patch "/article/:id", to: "articles#update"
  get "/article/:id", to: "articles#show", as: "article"
  get "/articles/:id/edit", to: "articles#edit", as: "article_edit" 
  get "/articles/new", to: "articles#new"
  get "/articles", to: "articles#index"
  post "/articles", to: "articles#create"
  root "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :name, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :birth, presence: true
  validates :gender, presence: true
  validate :validate_gender
  belongs_to :user

  enum role: [:member, :admin, :superadmin]

  after_create :set_role 

  private
  def validate_gender
    unless self.gender == 'Male' || self.gender == 'Female'
      errors.add(:gender, "Was specified incorrectly")
    end
  end

  def set_role
    self.update(role: 0)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, length: { minimum: 6 }
  has_secure_password
  has_many :articles
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :user_has_profile?
  helper_method :current_user

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  private 

  def authenticate_user!
    redirect_to login_path, notice: "You have to be logged in." unless current_user
  end

  def user_has_profile?
    if current_user && current_user.profile.nil?
      redirect_to new_profile_path, notice: 'Tell us more about you'
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  def index
    @articles = Article.all
  end
  def new
    @article = Article.new
  end

  def show
  end

  def edit
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to articles_path, notice: "Article was created."
    else 
      render :new, status: :unprocessable_entity  
    end
  end

  def update
    if @article.update(article_params)
      redirect_to article_path(@article), notice: "Article was updated."
    else 
      render :edit, status: :unprocessable_entity  
    end 
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  def article_params 
    params.require(:article).permit(:name, :description)
  end
  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @num = 100
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :user_has_profile?, only: %i[new create]
  before_action :set_profile, only: %i[ show edit update destroy ]

  def index
    @profiles = Profile.all
  end

  def show
  end

  def new
    @profile = Profile.new
  end

  def edit
  end

  def create
    @profile = current_user.build_profile(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @profile.destroy!

    respond_to do |format|
      format.html { redirect_to profiles_path, status: :see_other, notice: "Profile was successfully destroyed." }
    end
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:name, :city, :country, :birth, :gender, :role)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[login create]
  def login
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user.present? && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Login successfully"
    else
      redirect_to login_path, notice: "Email or password incorrect"
    end
  end

  def destroy
    session[:user_id] = nil 
    redirect_to login_path, notice: "Logout successfully" 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new create]
  before_action :set_user, only: %i[show edit update destroy]
  def new
    @user = User.new
  end

  def show
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'User was updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Sign up successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @users = User.all
  end

  def destroy
    session[:user_id] = nil if current_user == @user
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted.'
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div>
    <%= form_with(model: @article) do |form| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

            <ul>
            <% @article.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
        <div>
            <%= form.label :name, 'Insert name:' %>
            <%= form.text_field :name %>
        </div>
        <div>
            <%= form.label :description, 'Insert description:' %>
            <%= form.text_field :description %>
        </div>
        <div>
            <%= form.submit %>
        </div>
    <% end %>
</div>

app/views/articles/edit.html.erb
<h2>Edit Article</h2>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<% @articles.each do |article| %>
  <div>
    <strong><%= article.name %></strong><br>
    <%= article.description %><br>
    <%= link_to 'See more', article_path(article) %><br>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Show Article</h1>
<div>
    <h3> <%= @article.name %> </h3>
    <div>
        <%= @article.description %>
    </div>
    <div>
        <%= link_to 'Edit article', article_edit_path(@article) %>
        <%= button_to 'Delete article', article_destroy_path(@article), method: :delete %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= notice if notice %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Hello world!</h1>
<h2><%= @num %></h2>

<% if @num > 100 %>
    <p>Número es mayor a 100</p>
<% else %>
    <p>Número no es mayor a 100</p>
<% end %>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :birth, style: "display: block" %>
    <%= form.date_field :birth %>
  </div>

  <div>
    <%= form.radio_button :gender, "Male" %>
    <%= form.label :gender, "Male" %>
    <%= form.radio_button :gender, "Female" %>
    <%= form.label :gender, "Female" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
  <p>
    <strong>Name:</strong>
    <%= profile.name %>
  </p>

  <p>
    <strong>City:</strong>
    <%= profile.city %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= profile.country %>
  </p>

  <p>
    <strong>Birth:</strong>
    <%= profile.birth %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= profile.gender %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= profile.role %>
  </p>

  <p>
    <strong>User:</strong>
    <%= profile.user_id %>
  </p>

</div>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Show this profile", @profile %> |
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Profiles</h1>

<div id="profiles">
  <% @profiles.each do |profile| %>
    <%= render profile %>
    <p>
      <%= link_to "Show this profile", profile %>
    </p>
  <% end %>
</div>

<%= link_to "New profile", new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @profile %>

<div>
  <%= link_to "Edit this profile", edit_profile_path(@profile) %> |
  <%= link_to "Back to profiles", profiles_path %>

  <%= button_to "Destroy this profile", @profile, method: :delete %>
</div>

app/views/shared/_header.html.erb
<nav>
    <ul>
        <li><%= link_to 'Rails App', root_path %></li>
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <li><%= link_to 'New article', articles_new_path %></li>
        <% if current_user %>
            <li> <%= button_to 'Log out', logout_path, method: :delete %> </li>
            <li>
                <%= current_user.email %>
            </li>
        <% else %>
            <li><%= link_to 'Login', login_path %></li>
            <li><%= link_to 'Sign up', signup_path %></li>
        <% end %>
    </ul>
</nav>

app/views/users/_form.html.erb
<div>
    <%= form_with(model: @user) do |form| %>
        <% if @user.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

                <ul>
                <% @user.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
                </ul>
            </div>
        <% end %>
        <div>
            <%= form.label :email %>
            <%= form.email_field :email %>
        </div>
        <div>
            <%= form.label :password %>
            <%= form.password_field :password %>
        </div>
        <div>
            <%= form.label :password_confirmation %>
            <%= form.password_field :password_confirmation %>
        </div>
        <div>
            <%= form.submit buttonText %>
        </div>
    <% end %>
</div>

app/views/users/_user.html.erb
<div>
    <%= user.email %> <br>
    <%= link_to 'See user', user_path(user) %>
</div>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= render 'form', buttonText: 'Update account' %>

app/views/users/index.html.erb
<h1>Users</h1>
<div>
<% @users.each do |user| %>
    <%= render 'user', user: user %>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render 'form', buttonText: 'Sign up' %>

app/views/users/show.html.erb
<h1>User</h1>
<div>
    <%= @user.email %> <br>
    <%= link_to 'Edit User', user_edit_path(@user) %><br>
    <%= button_to 'Delete User', user_destroy_path(@user), method: :delete %><br>
</div>